### ISSUE TITLE
What's the mininum GPU memory size required?

### ISSUE THREAD

**Issue by dragen1860** [brain-research/acai#3]
Hi, when I run `python create_dataset.py` and an error of `OUT OF GPU MEMORY` occured.
I wonder what's the minimum GPU memory size required.
My own hardware is GTX 1050 with 4GB mem.

**Comment by craffel** [comment]
Hi Jackie, we used GCE k80s for all experiments but I don't think you should run out of memory, especially when running `create_dataset.py`. Are you running other TensorFlow processes? TensorFlow likes to grab all the memory on the GPU whenever it starts up so it can fail when there are multiple processes running.

**Comment by david-berthelot** [comment]
When creating  datasets there's no real need for GPU, try running it like this:
```
CUDA_VISIBLE_DEVICES= python create_datasets.py
```

**Comment by dragen1860** [comment]
HI, I found it works with python 2.7. It will trigger out of memory when running under python 3.6.
Nevermind, I will read your code under py27.
