### ISSUE TITLE
Do you write baseline.py/aae.py/dropout.py/denoising.py from scratch?

### ISSUE THREAD

**Issue by dragen1860** [brain-research/acai#5]
Dear author:
  you compared your acai method with several baselines. I wonder do you implement these baselines by yourself from scratch, or you simply refereed others implementation.
  If you implement these baselines from scratch, your coding skill is really excellent.

**Comment by david-berthelot** [comment]
For baseline, dropout and denoising, it was from scratch. For aae, we need to ask Colin.

**Comment by craffel** [comment]
Yes, all completely from scratch.

**Comment by dragen1860** [comment]
Great!
