### ISSUE TITLE
Why No reuse=True setted?

### ISSUE THREAD

**Issue by dragen1860** [brain-research/acai#6]
Dear author:
   I feel sorry cause this is a tensorflow technical problem, but I will greatly appreciate that if you can answer that.
In lib/train.py, you try to get variable with name `name` and put it into summary. However, my question is , You have not set `reuse=True` so will that be a potential problem??

Thanks.
```python
    @staticmethod
    def add_summary_var(name):
        """
        add variable name into summary, and name it 'name' in summary
        :param name: 
        :return: 
        """
        v = tf.get_variable(name, [], trainable=False, initializer=tf.initializers.zeros())
        tf.summary.scalar(name, v)
        return v
```
You call it without setting reuse=true:
```python
        with tf.Graph().as_default():

            data_in = self.train_data.make_one_shot_iterator().get_next()
            global_step = tf.train.get_or_create_global_step()

            self.latent_accuracy = self.add_summary_var('latent_accuracy')
            self.mean_smoothness = self.add_summary_var('mean_smoothness')
            self.mean_distance = self.add_summary_var('mean_distance')
```

**Comment by david-berthelot** [comment]
There's no need to do reuse since the 'add_summary_var' method is called only once.

**Comment by dragen1860** [comment]
Then you mean get_variable will create a new variable with name?

**Comment by david-berthelot** [comment]
Yes get_variable creates a new variable with the given name.

**Comment by dragen1860** [comment]
OK, i see.
