### ISSUE TITLE
Why so many xxx<<10?

### ISSUE THREAD

**Issue by dragen1860** [brain-research/acai#8]
hi ,dear author:
  I notice you used a lot of `xxx<<10` in your source as:
```python
            summary_hook = tf.train.SummarySaverHook(
                save_steps=(report_kimg << 10) // batch_size,
                output_dir=self.summary_dir,
                summary_op=tf.summary.merge_all())
            stop_hook = tf.train.StopAtStepHook(last_step=1 + (FLAGS.total_kimg << 10) // batch_size)
            report_hook = utils.HookReport(report_kimg << 10, batch_size)
```
I dnt understand this because both `report_img`(1<<6) and `FLAGS.total_kimg`(1<<14) are the real number given already.
Why you enlarge them by `<<10` once again?

**Comment by david-berthelot** [comment]
The unit is kimg (kibi-images):
https://en.wikipedia.org/wiki/Kibibyte

**Comment by dragen1860** [comment]
Thanks, Hoever,
I know the meaning of symbol `<<`. I just curious why not set `report_kimg = report << 10` directly instead of enlarging value of `report_kimg` every time.
